options:
  command_name:
    name: Command Name
    notes: The name of the command to pull statistics for.
    default: mongrel_rails
  ps_command:
    name: The Process Status (ps) Command
    notes: The command with options. The default works on most systems.
    default: ps axucww
  ps_regex:
    name: The regex used to match a command name.
    notes: "By default, this matches a command with options at the end of a line.  The word COMMAND get's replaced with the command you gave (regex escaped).  You may wish to try the following pattern if you have trouble matching dynamic options:  (?i:\\bCOMMAND\\b)"
    default: "(?i:COMMAND\\s+$)"
    
metadata:
  memory:          
    label: Memory Usage
    units: MB
    precision: 0
    
triggers:
  - type: peak
    data_series_name: memory
    max_value: 10
  - type: trend
    data_series_name: memory
    direction: UP
    percentage_change: 20
    duration: 60
    window_reference: LAST_WEEK
    min_value: 5