options:
  url:
    name: Url
    notes: The full URL (including http://) of the URL to monitor. You can provide basic authentication options as well (http://user:pass@domain.com)
    default: "http://www.scoutapp.com/"

metadata:
  up:          
    label: Url Reachable
    precision: 0
            
triggers:
  - type: trend
    data_series_name: up
    direction: EITHER
    percentage_change: 20
    duration: 60
    window_reference: LAST_WEEK
