options:
  log:
    name: Full Path to Rails Log File
    notes: "The full path to the Ruby on Rails log file you wish to analyze (ex: /var/www/apps/APP_NAME/current/log/production.log)."
  max_request_length:
    name: Max Request Length (sec)
    notes: If any request length is larger than this amount, an alert is generated (see Advanced for more options)
    default: 3
  rla_run_time:
    name: Request Log Analyzer Run Time (HH:MM)
    notes: It's best to schedule these summaries about fifteen minutes before any logrotate cron job you have set would kick in.
    default: '23:45'
    advanced: true
  ignored_actions:
    name: Ignored Actions
    notes: Takes a regex. Any URIs matching this regex will NOT count as slow requests, and you will NOT be notified if they exceed Max Request Length. Matching actions will still be included in daily summaries.
    advanced: true

metadata:
  request_rate:
    precision: 2
    label: Requests
    units: req/min
  average_request_length:
    precision: 2
    units: sec
  slow_request_rate:
    precision: 2
    label: Slow Requests
    units: req/min
    
triggers:
  - type: trend
    dname: request_rate
    direction: UP
    percentage_change: 200
    duration: 60
    window_reference: LAST_WEEK
    min_value: 100
  - type: trend
    dname: average_request_length
    direction: UP
    percentage_change: 200
    duration: 60
    window_reference: LAST_WEEK
    min_value: 0.3 