options:
  mysql_slow_log:
    default: /var/log/mysql/mysql-slow.log #/var/log/mysql/mysql-slow.log
    name: Full path to the MySQL slow queries log file

metadata:
  slow_queries:
    units: /sec
    precision: 2
triggers:
  - type: peak
    dname: slow_queries
    max_value: 1
  - type: trend
    dname: slow_queries
    direction: UP
    percentage_change: 30
    duration: 120
    window_reference: LAST_WEEK
    min_value: 100