options:
  mysql_slow_log:
    default: /var/log/mysql/mysql-slow.log
    name: Full path to the MySQL slow queries log file
  minimum_query_time:
    default: 0
    name: "Minimum Query Time (sec)"
    attributes: advanced
    notes: If the log file contains queries that are less than the specified time in seconds the queries will be ignored.
metadata:
  slow_queries:
    units: /min
    precision: 2
triggers:
  - type: trend
    dname: slow_queries
    direction: UP
    percentage_change: 30
    duration: 120
    window_reference: LAST_WEEK
    min_value: 0.3