metadata:
  last_minute:
    precision: 2
  last_five_minutes:
    precision: 2
  last_fifteen_minutes:
    precision: 2

triggers:
  - type: peak
    dname: last_minute
    max_value: 3
  - type: trend
    dname: last_minute
    direction: UP
    percentage_change: 60
    duration: 60
    window_reference: LAST_WEEK
    min_value: 0.2